<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $authors = Author::pluck('id', 'slug')->toArray();
        $categories = Category::pluck('id', 'slug')->toArray();

        $books = [
            // === Fiction & Literature (7 books) ===
            [
                'title' => "Les Mis\u00e9rables",
                'slug' => 'les-miserables',
                'isbn' => '978-2-07-040922-8',
                'author' => 'victor-hugo',
                'category' => 'fiction-litterature',
                'description' => "Dans la France du XIXe si\u00e8cle, Jean Valjean, ancien for\u00e7at, tente de se racheter et de mener une vie honn\u00eate malgr\u00e9 la traque impitoyable de l'inspecteur Javert. Cette fresque sociale monumentale explore la r\u00e9demption, la justice et l'amour \u00e0 travers des personnages inoubliables.",
                'publisher' => 'Gallimard',
                'publication_year' => 1862,
                'pages' => 1464,
                'language' => 'fr',
            ],
            [
                'title' => '1984',
                'slug' => '1984',
                'isbn' => '978-2-07-041180-1',
                'author' => 'george-orwell',
                'category' => 'fiction-litterature',
                'description' => "Dans un r\u00e9gime totalitaire o\u00f9 Big Brother surveille chaque geste, Winston Smith tente de pr\u00e9server son humanit\u00e9 et sa libert\u00e9 de pens\u00e9e. Ce roman dystopique visionnaire reste plus pertinent que jamais dans notre monde de surveillance de masse.",
                'publisher' => 'Gallimard',
                'publication_year' => 1949,
                'pages' => 328,
                'language' => 'fr',
            ],
            [
                'title' => "Le Petit Prince",
                'slug' => 'le-petit-prince',
                'isbn' => '978-2-07-040923-5',
                'author' => 'antoine-de-saint-exupery',
                'category' => 'fiction-litterature',
                'description' => "Un pilote \u00e9chou\u00e9 dans le d\u00e9sert rencontre un myst\u00e9rieux petit prince venu d'une autre plan\u00e8te. \u00c0 travers leurs \u00e9changes po\u00e9tiques, ce conte philosophique explore les secrets de l'amiti\u00e9, de l'amour et de l'essentiel qui est invisible pour les yeux.",
                'publisher' => 'Gallimard',
                'publication_year' => 1943,
                'pages' => 96,
                'language' => 'fr',
            ],
            [
                'title' => "Cent Ans de Solitude",
                'slug' => 'cent-ans-de-solitude',
                'isbn' => '978-2-02-028653-0',
                'author' => 'gabriel-garcia-marquez',
                'category' => 'fiction-litterature',
                'description' => "L'histoire l\u00e9gendaire de la famille Buend\u00eda dans le village mythique de Macondo, sur plusieurs g\u00e9n\u00e9rations m\u00ealant r\u00e9alit\u00e9 et fantastique. Ce chef-d'\u0153uvre du r\u00e9alisme magique a r\u00e9volutionn\u00e9 la litt\u00e9rature latino-am\u00e9ricaine et marqu\u00e9 le monde entier.",
                'publisher' => 'Seuil',
                'publication_year' => 1967,
                'pages' => 448,
                'language' => 'fr',
            ],
            [
                'title' => "Orgueil et Pr\u00e9jug\u00e9s",
                'slug' => 'orgueil-et-prejuges',
                'isbn' => '978-2-07-041183-2',
                'author' => 'jane-austen',
                'category' => 'fiction-litterature',
                'description' => "Elizabeth Bennet, jeune femme intelligente et ind\u00e9pendante, doit naviguer dans les conventions sociales de l'Angleterre georgienne tout en affrontant ses propres pr\u00e9jug\u00e9s. Une satire brillante des m\u0153urs victoriennes et une histoire d'amour intemporelle.",
                'publisher' => 'Gallimard',
                'publication_year' => 1813,
                'pages' => 432,
                'language' => 'fr',
            ],
            [
                'title' => "Kafka sur le Rivage",
                'slug' => 'kafka-sur-le-rivage',
                'isbn' => '978-2-07-042199-2',
                'author' => 'haruki-murakami',
                'category' => 'fiction-litterature',
                'description' => "Deux r\u00e9cits parall\u00e8les s'entrelacent : celui de Kafka Tamura, un adolescent fuyant une proph\u00e9tie \u0153dipienne, et celui de Nakata, un vieillard capable de parler avec les chats. Un roman onirique et envo\u00fbtant o\u00f9 la fronti\u00e8re entre r\u00e9alit\u00e9 et fantastique s'estompe.",
                'publisher' => 'Gallimard',
                'publication_year' => 2002,
                'pages' => 640,
                'language' => 'fr',
            ],
            [
                'title' => "Harry Potter \u00e0 l'\u00c9cole des Sorciers",
                'slug' => 'harry-potter-a-lecole-des-sorciers',
                'isbn' => '978-2-07-051842-5',
                'author' => 'jk-rowling',
                'category' => 'fiction-litterature',
                'description' => "Le jeune Harry Potter d\u00e9couvre le jour de ses onze ans qu'il est un sorcier et int\u00e8gre l'\u00e9cole de sorcellerie de Poudlard. Commence alors une aventure magique o\u00f9 l'amiti\u00e9, le courage et les forces du mal s'affrontent dans un monde fabuleux.",
                'publisher' => 'Gallimard',
                'publication_year' => 1997,
                'pages' => 320,
                'language' => 'fr',
            ],
            // === Science & Mathematics (3 books) ===
            [
                'title' => "Une Br\u00e8ve Histoire du Temps",
                'slug' => 'une-breve-histoire-du-temps',
                'isbn' => '978-2-08-081238-4',
                'author' => 'stephen-hawking',
                'category' => 'sciences',
                'description' => "Du Big Bang aux trous noirs, Stephen Hawking nous guide \u00e0 travers les myst\u00e8res de l'univers avec une clart\u00e9 remarquable. Ce best-seller mondial rend accessibles les th\u00e9ories les plus complexes de la physique moderne.",
                'publisher' => 'Flammarion',
                'publication_year' => 1988,
                'pages' => 256,
                'language' => 'fr',
            ],
            [
                'title' => 'The Grand Design',
                'slug' => 'the-grand-design',
                'isbn' => '978-0-553-80537-6',
                'author' => 'stephen-hawking',
                'category' => 'sciences',
                'description' => "Stephen Hawking explores the fundamental questions of existence: why is there something rather than nothing? With clarity and wit, he explains M-theory and the latest cosmological discoveries that shape our understanding of the universe.",
                'publisher' => 'Bantam Books',
                'publication_year' => 2010,
                'pages' => 208,
                'language' => 'en',
            ],
            [
                'title' => 'The Universe in a Nutshell',
                'slug' => 'the-universe-in-a-nutshell',
                'isbn' => '978-0-553-80538-3',
                'author' => 'stephen-hawking',
                'category' => 'sciences',
                'description' => "Illustrated with stunning full-color images, this book takes us on a fascinating journey through space-time, relativity, and quantum physics. An invitation to contemplate the wonders of the cosmos.",
                'publisher' => 'Bantam Books',
                'publication_year' => 2001,
                'pages' => 224,
                'language' => 'en',
            ],
            // === History & Geography (4 books) ===
            [
                'title' => "Sapiens : Une Br\u00e8ve Histoire de l'Humanit\u00e9",
                'slug' => 'sapiens',
                'isbn' => '978-2-253-17465-3',
                'author' => 'yuval-noah-harari',
                'category' => 'histoire',
                'description' => "De l'apparition d'Homo Sapiens \u00e0 la r\u00e9volution num\u00e9rique, ce livre retrace les grandes \u00e9tapes de l'histoire humaine avec une perspective novatrice. Une r\u00e9flexion passionnante sur notre pass\u00e9 qui \u00e9claire notre pr\u00e9sent.",
                'publisher' => 'Albin Michel',
                'publication_year' => 2011,
                'pages' => 512,
                'language' => 'fr',
            ],
            [
                'title' => "M\u00e9moires d'Hadrien",
                'slug' => 'memoires-dhadrien',
                'isbn' => '978-2-07-036921-8',
                'author' => 'marguerite-yourcenar',
                'category' => 'histoire',
                'description' => "Sur son lit de mort, l'empereur romain Hadrien dicte ses m\u00e9moires \u00e0 son successeur Marc-Aur\u00e8le. Yourcenar signe un chef-d'\u0153uvre historique d'une \u00e9rudition et d'une beaut\u00e9 litt\u00e9raire exceptionnelles.",
                'publisher' => 'Gallimard',
                'publication_year' => 1951,
                'pages' => 364,
                'language' => 'fr',
            ],
            [
                'title' => "Le Monde s'Effondre",
                'slug' => 'le-monde-seffondre',
                'isbn' => '978-2-7087-0686-0',
                'author' => 'chinua-achebe',
                'category' => 'histoire',
                'description' => "Dans le Nigeria pr\u00e9colonial, Okonkwo, guerrier respect\u00e9 du clan Ibo, voit son monde s'effondrer avec l'arriv\u00e9e des missionnaires blancs. Ce roman fondateur de la litt\u00e9rature africaine raconte la trag\u00e9die de la colonisation.",
                'publisher' => "Pr\u00e9sence Africaine",
                'publication_year' => 1958,
                'pages' => 224,
                'language' => 'fr',
            ],
            [
                'title' => "Les Croisades vues par les Arabes",
                'slug' => 'les-croisades-vues-par-les-arabes',
                'isbn' => '978-2-01-279403-6',
                'author' => 'amin-maalouf',
                'category' => 'histoire',
                'description' => "Amin Maalouf raconte l'\u00e9pop\u00e9e des Croisades du point de vue arabe, en s'appuyant sur les chroniques de l'\u00e9poque. Un \u00e9clairage pr\u00e9cieux et passionnant qui renverse la perspective occidentale traditionnelle.",
                'publisher' => 'Latt\u00e8s',
                'publication_year' => 1983,
                'pages' => 320,
                'language' => 'fr',
            ],
            // === Technology & Computing (3 books) ===
            [
                'title' => "Homo Deus : Une Br\u00e8ve Histoire du Futur",
                'slug' => 'homo-deus',
                'isbn' => '978-2-253-08807-3',
                'author' => 'yuval-noah-harari',
                'category' => 'technologie',
                'description' => "Apr\u00e8s avoir conquis la plan\u00e8te, l'humanit\u00e9 se tourne vers de nouveaux d\u00e9fis : l'immortalit\u00e9, la qu\u00eate du bonheur et la divinisation technologique. Une analyse fascinante des possibles futurs de notre esp\u00e8ce.",
                'publisher' => 'Albin Michel',
                'publication_year' => 2015,
                'pages' => 448,
                'language' => 'fr',
            ],
            [
                'title' => "21 Le\u00e7ons pour le XXIe Si\u00e8cle",
                'slug' => '21-lecons-pour-le-xxie-siecle',
                'isbn' => '978-2-253-23727-3',
                'author' => 'yuval-noah-harari',
                'category' => 'technologie',
                'description' => "Face \u00e0 la r\u00e9volution technologique, au changement climatique et aux crises politiques, quelles sont les comp\u00e9tences dont nous aurons besoin ? Harari examine les d\u00e9fis br\u00fblants de notre \u00e9poque avec lucidit\u00e9 et profondeur.",
                'publisher' => 'Albin Michel',
                'publication_year' => 2018,
                'pages' => 400,
                'language' => 'fr',
            ],
            [
                'title' => "Apocalypse Postponed",
                'slug' => 'apocalypse-postponed',
                'isbn' => '978-0-253-33160-2',
                'author' => 'umberto-eco',
                'category' => 'technologie',
                'description' => "Umberto Eco analyse les m\u00e9dias de masse, la culture populaire et l'impact des nouvelles technologies sur la soci\u00e9t\u00e9 contemporaine. Une r\u00e9flexion incisive sur la communication \u00e0 l'\u00e8re des r\u00e9seaux et de l'information globale.",
                'publisher' => 'Indiana University Press',
                'publication_year' => 1994,
                'pages' => 240,
                'language' => 'en',
            ],
            // === Philosophy & Psychology (3 books) ===
            [
                'title' => "Le Proph\u00e8te",
                'slug' => 'le-prophete',
                'isbn' => '978-2-07-041184-9',
                'author' => 'khalil-gibran',
                'category' => 'philosophie',
                'description' => "Le proph\u00e8te Almustafa s'appr\u00eate \u00e0 quitter la ville d'Orphal\u00e8se apr\u00e8s douze ans d'exil. Avant son d\u00e9part, le peuple le supplie de partager sa sagesse sur l'amour, le mariage, les enfants, le travail, la joie et la peine.",
                'publisher' => 'Gallimard',
                'publication_year' => 1923,
                'pages' => 112,
                'language' => 'fr',
            ],
            [
                'title' => "Le Discours de la M\u00e9thode",
                'slug' => 'le-discours-de-la-methode',
                'isbn' => '978-2-08-070593-8',
                'author' => 'rene-descartes',
                'category' => 'philosophie',
                'description' => "Descartes \u00e9tablit les r\u00e8gles d'une m\u00e9thode pour bien conduire sa raison et chercher la v\u00e9rit\u00e9 dans les sciences. Ce texte fondateur de la philosophie moderne introduit le fameux \"Je pense, donc je suis\" et la m\u00e9thode du doute syst\u00e9matique.",
                'publisher' => 'Flammarion',
                'publication_year' => 1637,
                'pages' => 128,
                'language' => 'fr',
            ],
            [
                'title' => "Le Mythe de Sisyphe",
                'slug' => 'le-mythe-de-sisyphe',
                'isbn' => '978-2-07-036028-4',
                'author' => 'albert-camus',
                'category' => 'philosophie',
                'description' => "Camus explore la question fondamentale du suicide face \u00e0 l'absurdit\u00e9 de l'existence. \u00c0 travers le mythe de Sisyphe, condamn\u00e9 \u00e0 rouler \u00e9ternellement un rocher, il d\u00e9montre que la r\u00e9volte et la libert\u00e9 int\u00e9rieure donnent un sens \u00e0 la vie.",
                'publisher' => 'Gallimard',
                'publication_year' => 1942,
                'pages' => 192,
                'language' => 'fr',
            ],
            // === Arts & Music (3 books) ===
            [
                'title' => "\u00c9thiopiques",
                'slug' => 'ethiopiques',
                'isbn' => '978-2-02-001321-1',
                'author' => 'leopold-sedar-senghor',
                'category' => 'arts',
                'description' => "Recueil po\u00e9tique majeur de L\u00e9opold S\u00e9dar Senghor, o\u00f9 la n\u00e9gritude s'exprime \u00e0 travers des vers lyriques et incantatoires. Un hymne \u00e0 la beaut\u00e9 de l'Afrique, \u00e0 sa culture et \u00e0 son \u00e2me profonde.",
                'publisher' => 'Seuil',
                'publication_year' => 1956,
                'pages' => 128,
                'language' => 'fr',
            ],
            [
                'title' => 'Art and Beauty in the Middle Ages',
                'slug' => 'art-and-beauty-in-the-middle-ages',
                'isbn' => '978-0-300-03676-3',
                'author' => 'umberto-eco',
                'category' => 'arts',
                'description' => "Umberto Eco examines medieval aesthetic theories and the concept of beauty as understood by thinkers of the Middle Ages. A fascinating exploration of how art, philosophy, and theology intertwined in medieval culture.",
                'publisher' => 'Yale University Press',
                'publication_year' => 1986,
                'pages' => 144,
                'language' => 'en',
            ],
            [
                'title' => "Le Temps, ce grand sculpteur",
                'slug' => 'le-temps-ce-grand-sculpteur',
                'isbn' => '978-2-07-070355-3',
                'author' => 'marguerite-yourcenar',
                'category' => 'arts',
                'description' => "Recueil d'essais de Marguerite Yourcenar sur l'art, l'histoire et la litt\u00e9rature. De la sculpture antique \u00e0 la peinture flamande, elle d\u00e9ploie une \u00e9rudition lumineuse et une sensibilit\u00e9 esth\u00e9tique hors du commun.",
                'publisher' => 'Gallimard',
                'publication_year' => 1983,
                'pages' => 256,
                'language' => 'fr',
            ],
            // === Business & Economics (3 books) ===
            [
                'title' => "Le Capital au XXIe Si\u00e8cle",
                'slug' => 'le-capital-au-xxie-siecle',
                'isbn' => '978-2-02-108241-0',
                'author' => 'thomas-piketty',
                'category' => 'business',
                'description' => "Thomas Piketty analyse l'\u00e9volution des in\u00e9galit\u00e9s sur trois si\u00e8cles \u00e0 travers une enqu\u00eate historique et statistique sans pr\u00e9c\u00e9dent. Un ouvrage majeur qui a renouvel\u00e9 le d\u00e9bat \u00e9conomique mondial sur la r\u00e9partition des richesses.",
                'publisher' => 'Seuil',
                'publication_year' => 2013,
                'pages' => 976,
                'language' => 'fr',
            ],
            [
                'title' => "Capital et Id\u00e9ologie",
                'slug' => 'capital-et-ideologie',
                'isbn' => '978-2-02-133804-3',
                'author' => 'thomas-piketty',
                'category' => 'business',
                'description' => "Prolongeant son enqu\u00eate sur les in\u00e9galit\u00e9s, Piketty explore les id\u00e9ologies et les r\u00e9gimes politiques qui les ont fa\u00e7onn\u00e9es \u00e0 travers les \u00e9poques et les civilisations. Une proposition pour un socialisme participatif et d\u00e9centralis\u00e9 au XXIe si\u00e8cle.",
                'publisher' => 'Seuil',
                'publication_year' => 2019,
                'pages' => 1232,
                'language' => 'fr',
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'slug' => 'thinking-fast-and-slow',
                'isbn' => '978-0-374-53355-7',
                'author' => 'daniel-kahneman',
                'category' => 'business',
                'description' => "Daniel Kahneman reveals the two systems that drive the human mind: the fast, intuitive System 1 and the slow, deliberate System 2. A groundbreaking exploration of how we think, make decisions, and why we are often wrong.",
                'publisher' => 'Farrar, Straus and Giroux',
                'publication_year' => 2011,
                'pages' => 512,
                'language' => 'en',
            ],
            // === Health & Medicine (3 books) ===
            [
                'title' => "La Peste",
                'slug' => 'la-peste',
                'isbn' => '978-2-07-036042-0',
                'author' => 'albert-camus',
                'category' => 'sante',
                'description' => "Dans la ville d'Oran frapp\u00e9e par une \u00e9pid\u00e9mie de peste, le docteur Rieux lutte sans rel\u00e2che contre la maladie et l'indiff\u00e9rence. Une all\u00e9gorie puissante sur la r\u00e9sistance humaine face au mal et sur l'engagement collectif n\u00e9cessaire pour combattre l'adversit\u00e9.",
                'publisher' => 'Gallimard',
                'publication_year' => 1947,
                'pages' => 336,
                'language' => 'fr',
            ],
            [
                'title' => "L'Amour au temps du chol\u00e9ra",
                'slug' => 'lamour-au-temps-du-cholera',
                'isbn' => '978-2-02-041731-6',
                'author' => 'gabriel-garcia-marquez',
                'category' => 'sante',
                'description' => "Florentino Ariza et Fermina Daza vivent un amour interdit dans une ville carib\u00e9enne ravag\u00e9e par le chol\u00e9ra. Une histoire d'amour inoubliable sur plus d'un demi-si\u00e8cle, o\u00f9 la maladie sert de toile de fond \u00e0 une passion d\u00e9vorante.",
                'publisher' => 'Grasset',
                'publication_year' => 1985,
                'pages' => 416,
                'language' => 'fr',
            ],
            [
                'title' => "Trait\u00e9 des passions de l'\u00e2me",
                'slug' => 'traite-des-passions-de-lame',
                'isbn' => '978-2-08-070598-3',
                'author' => 'rene-descartes',
                'category' => 'sante',
                'description' => "Descartes explore le lien entre le corps et l'esprit, analysant les m\u00e9canismes des \u00e9motions et leur impact sur la sant\u00e9 physique et mentale. Une \u0153uvre pionni\u00e8re qui jette les bases de la psychophysiologie moderne.",
                'publisher' => 'Flammarion',
                'publication_year' => 1649,
                'pages' => 288,
                'language' => 'fr',
            ],
            // === Religion & Spirituality (3 books) ===
            [
                'title' => "L'Alchimiste",
                'slug' => 'lalchimiste',
                'isbn' => '978-2-290-00363-7',
                'author' => 'paulo-coelho',
                'category' => 'religion',
                'description' => "Santiago, un jeune berger andalou, part \u00e0 la recherche d'un tr\u00e9sor cach\u00e9 au pied des pyramides d'\u00c9gypte. Ce voyage initiatique est une m\u00e9taphore de la qu\u00eate spirituelle et de l'accomplissement de sa l\u00e9gende personnelle.",
                'publisher' => "J'ai Lu",
                'publication_year' => 1988,
                'pages' => 252,
                'language' => 'fr',
            ],
            [
                'title' => "Le P\u00e8lerin de Compostelle",
                'slug' => 'le-pelerin-de-compostelle',
                'isbn' => '978-2-290-05363-2',
                'author' => 'paulo-coelho',
                'category' => 'religion',
                'description' => "Paulo Coelho relate son p\u00e8lerinage sur le chemin de Saint-Jacques-de-Compostelle, une exp\u00e9rience spirituelle transformatrice. Ce r\u00e9cit autobiographique m\u00eale rencontres mystiques, \u00e9preuves initiatiques et enseignements ancestraux.",
                'publisher' => "J'ai Lu",
                'publication_year' => 1987,
                'pages' => 288,
                'language' => 'fr',
            ],
            [
                'title' => 'Brida',
                'slug' => 'brida',
                'isbn' => '978-2-290-00752-9',
                'author' => 'paulo-coelho',
                'category' => 'religion',
                'description' => "Brida, une jeune Irlandaise, entame un voyage spirituel \u00e0 la recherche de la sagesse et de la connaissance de soi. Guid\u00e9e par un ma\u00eetre et une sorci\u00e8re, elle explore les myst\u00e8res de la magie, de l'amour et de la spiritualit\u00e9 f\u00e9minine.",
                'publisher' => "J'ai Lu",
                'publication_year' => 1990,
                'pages' => 272,
                'language' => 'fr',
            ],
            // === Education & Languages (3 books) ===
            [
                'title' => "Les Identit\u00e9s meurtri\u00e8res",
                'slug' => 'les-identites-meurtrieres',
                'isbn' => '978-2-253-15022-0',
                'author' => 'amin-maalouf',
                'category' => 'education',
                'description' => "Amin Maalouf r\u00e9fl\u00e9chit sur la notion d'identit\u00e9 et les dangers du repli identitaire dans un monde globalis\u00e9. Un essai lumineux qui appelle \u00e0 une \u00e9ducation \u00e0 la tol\u00e9rance et \u00e0 la compr\u00e9hension entre les cultures.",
                'publisher' => "Le Livre de Poche",
                'publication_year' => 1998,
                'pages' => 240,
                'language' => 'fr',
            ],
            [
                'title' => "R\u00e8gles pour la direction de l'esprit",
                'slug' => 'regles-pour-la-direction-de-lesprit',
                'isbn' => '978-2-7116-0200-6',
                'author' => 'rene-descartes',
                'category' => 'education',
                'description' => "Descartes \u00e9nonce les r\u00e8gles fondamentales pour guider la pens\u00e9e vers la connaissance certaine. Ce trait\u00e9 m\u00e9thodologique pose les bases de la p\u00e9dagogie rationaliste et de la formation de l'esprit critique.",
                'publisher' => 'Vrin',
                'publication_year' => 1701,
                'pages' => 160,
                'language' => 'fr',
            ],
            [
                'title' => "Libert\u00e9 1 : N\u00e9gritude et Humanisme",
                'slug' => 'liberte-1-negritude-et-humanisme',
                'isbn' => '978-2-02-002475-0',
                'author' => 'leopold-sedar-senghor',
                'category' => 'education',
                'description' => "Premier volume des discours et essais de L\u00e9opold S\u00e9dar Senghor, o\u00f9 il expose sa vision de la n\u00e9gritude et de l'universalisme humaniste. Un plaidoyer pour une \u00e9ducation qui concilie les valeurs africaines et l'h\u00e9ritage universel.",
                'publisher' => 'Seuil',
                'publication_year' => 1964,
                'pages' => 448,
                'language' => 'fr',
            ],
        ];

        foreach ($books as $data) {
            $total = rand(3, 10);
            Book::firstOrCreate(
                ['slug' => $data['slug']],
                [
                    'title' => $data['title'],
                    'slug' => $data['slug'],
                    'isbn' => $data['isbn'],
                    'author_id' => $authors[$data['author']],
                    'category_id' => $categories[$data['category']],
                    'description' => $data['description'],
                    'cover_image' => null,
                    'quantity_total' => $total,
                    'quantity_available' => $total,
                    'language' => $data['language'],
                    'publisher' => $data['publisher'],
                    'publication_year' => (string) $data['publication_year'],
                    'pages' => $data['pages'],
                    'status' => 'available',
                    'popularity' => rand(50, 500),
                    'rating' => '0.00',
                    'is_active' => true,
                ]
            );
        }
    }
}
